interface ZIF_PARAM_CONST
  public .


  constants C_/SCWM/DE_HUTYP type ZDE_PARAM_ID2 value '/SCWM/DE_HUTYP' ##NO_TEXT.
  constants C_AA_TWOMH type ZDE_PARAM_ID2 value 'AA_TWOMH' ##NO_TEXT.
  constants C_ACTIVITY_PICK type ZDE_PARAM_ID2 value 'ACTIVITY_PICK' ##NO_TEXT.
  constants C_AUGRU type ZDE_PARAM_ID2 value 'AUGRU' ##NO_TEXT.
  constants C_CONS_PROCTY type ZDE_PARAM_ID2 value 'ZDE_PROCTY' ##NO_TEXT.
  constants C_CR_WT_WAITING_TIME type ZDE_PARAM_ID2 value 'CR_WT_WAITING_TIME' ##NO_TEXT.
  constants C_DEST_STORAGE_TYPE type ZDE_PARAM_ID2 value 'DEST_STORAGE_TYPE' ##NO_TEXT.
  constants C_DROPOFF_BIN_EMPTY_CART type ZDE_PARAM_ID2 value 'BIN_FOR_EMPTY_CART' ##NO_TEXT.
  constants C_EXCCODE_BIDF type ZDE_PARAM_ID2 value 'EXCCODE_BIDF' ##NO_TEXT.
  constants C_EXCCODE_BIDP type ZDE_PARAM_ID2 value 'EXCCODE_BIDP' ##NO_TEXT.
  constants C_EXCCODE_FLHU type ZDE_PARAM_ID2 value 'EXCCODE_FLHU' ##NO_TEXT.
  constants C_EXCCODE_SNERR type ZDE_PARAM_ID2 value 'EXCCODE_SNERR' ##NO_TEXT.
  constants C_EXCCODE_SPLIT type ZDE_PARAM_ID2 value 'EXCCODE_SPLIT' ##NO_TEXT.
  constants C_FULL_HUTYP_LIST type ZDE_PARAM_ID2 value 'FULL_HUTYP_LIST' ##NO_TEXT.
  constants C_HUTYPGRP type ZDE_PARAM_ID2 value 'HUTYPGRP' ##NO_TEXT.
  constants C_HU_IDENT_IS_NO type ZDE_PARAM_ID2 value 'HU_IDENT_IS_NO' ##NO_TEXT.
  constants C_HU_IDENT_REF type ZDE_PARAM_ID2 value 'HU_IDENT_REF' ##NO_TEXT.
  constants C_INDENTTAB01 type ZDE_PARAM_ID2 value 'INDENTTAB01' ##NO_TEXT.
  constants C_INDENTTAB02 type ZDE_PARAM_ID2 value 'INDENTTAB02' ##NO_TEXT.
  constants C_INDENTTAB03 type ZDE_PARAM_ID2 value 'INDENTTAB03' ##NO_TEXT.
  constants C_INDENTTAB04 type ZDE_PARAM_ID2 value 'INDENTTAB04' ##NO_TEXT.
  constants C_INDENTTAB05 type ZDE_PARAM_ID2 value 'INDENTTAB05' ##NO_TEXT.
  constants C_LARGEORDERS_WOCR type ZDE_PARAM_ID2 value 'LARGEORDERS_WOCR' ##NO_TEXT.
  constants C_LGTYP_CONV type ZDE_PARAM_ID2 value 'LGTYP_CONV' ##NO_TEXT.
  constants C_LGTYP_PARK_PICKCART type ZDE_PARAM_ID2 value 'LGTYP_PARK_PICKCART' ##NO_TEXT.
  constants C_LGTYP_PUTWALL type ZDE_PARAM_ID2 value 'LGTYP_PUTWALL' ##NO_TEXT.
  constants C_LGTYP_TOTE_REL type ZDE_PARAM_ID2 value 'LGTYP_TOTE_REL' ##NO_TEXT.
  constants C_MAP_THRESHOLD type ZDE_PARAM_ID2 value 'MAP_THRESHOLD' ##NO_TEXT.
  constants C_MARM_MEINH type ZDE_PARAM_ID2 value 'MARM_MEINH' ##NO_TEXT.
  constants C_MONITOR type ZDE_PARAM_ID2 value '/SCWM/MON' ##NO_TEXT.
  constants C_MON_ZPACK type ZDE_PARAM_ID2 value 'MON_ZPACK' ##NO_TEXT.
  constants C_PACK_DYN type ZDE_PARAM_ID2 value 'PACK_DYN' ##NO_TEXT.
  constants C_PACK_STAT type ZDE_PARAM_ID2 value 'PACK_STAT' ##NO_TEXT.
  constants C_PARAM_CONS type ZDE_PARAM_ID1 value 'ZCONS_0001' ##NO_TEXT.
  constants C_PARAM_ID type ZDE_PARAM_ID2 value 'SUBTEST' ##NO_TEXT.
  constants C_PARKING_STORAGE_TYPE type ZDE_PARAM_ID2 value 'PARKING_STORAGE_TYPE' ##NO_TEXT.
  constants C_PARTY_ROLE_CUST_PRINT type ZDE_PARAM_ID2 value 'PARTROLE_CUSTPRINT' ##NO_TEXT.
  constants C_PICK_DEF_STSS_1 type ZDE_PARAM_ID2 value 'PICK_DEF_STSS_1' ##NO_TEXT.
  constants C_PICK_DEF_STSS_2 type ZDE_PARAM_ID2 value 'PICK_DEF_STSS_2' ##NO_TEXT.
  constants C_PICK_STR_STSS_1 type ZDE_PARAM_ID2 value 'PICK_STR_STSS_1' ##NO_TEXT.
  constants C_PICK_STR_STSS_2 type ZDE_PARAM_ID2 value 'PICK_STR_STSS_2' ##NO_TEXT.
  constants C_PMAT_AAREA type ZDE_PARAM_ID2 value 'PMAT_AAREA' ##NO_TEXT.
  constants C_PMAT_CART_ID type ZDE_PARAM_ID2 value 'PMAT_CART_ID' ##NO_TEXT.
  constants C_PMAT_CART_VIRTUAL type ZDE_PARAM_ID2 value 'PMAT_CART_VIRTUAL' ##NO_TEXT.
  constants C_PMAT_MC_CONV type ZDE_PARAM_ID2 value 'PMAT_MC_CONV' ##NO_TEXT.
  constants C_PMAT_MC_NONCONV type ZDE_PARAM_ID2 value 'PMAT_MC_NONCONV' ##NO_TEXT.
  constants C_PMAT_PLANNED_SHIP type ZDE_PARAM_ID2 value 'PMAT_PLANNED_SHIP' ##NO_TEXT.
  constants C_PMAT_PROF_P1PC type ZDE_PARAM_ID2 value 'PMAT_PROF_P1PC' ##NO_TEXT.
  constants C_PMAT_PROF_PSLO type ZDE_PARAM_ID2 value 'PMAT_PROF_PSLO' ##NO_TEXT.
  constants C_PMAT_SPED_PALLET type ZDE_PARAM_ID2 value 'PMAT_SPED_PALLET' ##NO_TEXT.
  constants C_PMAT_TOTE type ZDE_PARAM_ID2 value 'PMAT_TOTE' ##NO_TEXT.
*  CONSTANTS c_posc_kep_wpt TYPE zde_param_id2 VALUE 'POSC_KEP_WPT' ##NO_TEXT.
  constants C_POSC_SVK_HUTGR_NONC type ZDE_PARAM_ID2 value 'POSC_SVK_HUTGR_NONC' ##NO_TEXT.
  constants C_PRINT_HU_LAST type ZDE_PARAM_ID2 value 'PRINT_HU_LAST' ##NO_TEXT.
  constants C_PROCESS_ID type ZDE_PARAM_ID1 value 'IDTEST' ##NO_TEXT.
  constants C_PROCTY_KEP type ZDE_PARAM_ID2 value 'PROCTY_KEP' ##NO_TEXT.
  constants C_PROCTY_PUTWALL type ZDE_PARAM_ID2 value 'PROCTY_PUTWALL' ##NO_TEXT.
  constants C_PROCTY_SPED type ZDE_PARAM_ID2 value 'PROCTY_SPED' ##NO_TEXT.
  constants C_PROGRAM_VARAINT type ZDE_PARAM_ID2 value 'PROGRAM_VARIANT' ##NO_TEXT.
  constants C_PUTWALL_AAREA type ZDE_PARAM_ID2 value 'PUTWALL_AAREA' ##NO_TEXT.
  constants C_PUTWALL_WOCR type ZDE_PARAM_ID2 value 'PUTWALL_WOCR' ##NO_TEXT.
  constants C_PUT_CTR_IND type ZDE_PARAM_ID2 value 'PUT_CTR_IND' ##NO_TEXT.
  constants C_ROT_THRESHOLD type ZDE_PARAM_ID2 value 'ROT_THRESHOLD' ##NO_TEXT.
  constants C_ST_TYPE_EXCEPT type ZDE_PARAM_ID2 value 'ST_TYPE_EXCEPT' ##NO_TEXT.
  constants C_TEXT_TYPE_PACK_INST type ZDE_PARAM_ID2 value 'TEXT_TYPE_PACK_INST' ##NO_TEXT.
  constants C_WH_PROCESS_TYPE type ZDE_PARAM_ID2 value 'WH_PROCESS_TYPE' ##NO_TEXT.
  constants C_ZCONS_0001 type ZDE_PARAM_ID1 value 'ZCONS_0001' ##NO_TEXT.
  constants C_ZCROSS type ZDE_PARAM_ID1 value 'ZCROSS' ##NO_TEXT.
  constants C_ZCROSS_0002 type ZDE_PARAM_ID1 value 'ZCROSS_0002' ##NO_TEXT.
  constants C_ZCROSS_0003 type ZDE_PARAM_ID1 value 'ZCROSS_0003' ##NO_TEXT.
  constants C_ZCROSS_0004 type ZDE_PARAM_ID1 value 'ZCROSS_0004' ##NO_TEXT.
  constants C_ZCROSS_0005 type ZDE_PARAM_ID1 value 'ZCROSS_0005' ##NO_TEXT.
  constants C_ZDE_PUT_RULE type ZDE_PARAM_ID2 value 'ZDE_PUT_RULE' ##NO_TEXT.
  constants C_ZDE_SPLITPUT_LGTYP type ZDE_PARAM_ID2 value 'ZDE_SPLITPUT_LGTYP' ##NO_TEXT.
  constants C_ZGEN_0001 type ZDE_PARAM_ID1 value 'ZGEN_0001' ##NO_TEXT.
  constants C_ZGEN_0002 type ZDE_PARAM_ID1 value 'ZGEN_0002' ##NO_TEXT.
  constants C_ZGEN_0003 type ZDE_PARAM_ID1 value 'ZGEN_0003' ##NO_TEXT.
  constants C_ZGEN_0004 type ZDE_PARAM_ID1 value 'ZGEN_0004' ##NO_TEXT.
  constants C_ZGEN_0005 type ZDE_PARAM_ID1 value 'ZGEN_0005' ##NO_TEXT.
  constants C_ZGEN_0006 type ZDE_PARAM_ID1 value 'ZGEN_0006' ##NO_TEXT.
  constants C_ZINB_0001 type ZDE_PARAM_ID1 value 'ZINB_0001' ##NO_TEXT.
  constants C_ZINB_0002 type ZDE_PARAM_ID1 value 'ZINB_0002' ##NO_TEXT.
  constants C_ZINT_0001 type ZDE_PARAM_ID1 value 'ZINT_0001' ##NO_TEXT.
  constants C_ZMON_0001 type ZDE_PARAM_ID1 value 'ZMON_0001' ##NO_TEXT.
  constants C_ZOUT_0001 type ZDE_PARAM_ID1 value 'ZOUT_0001' ##NO_TEXT.
  constants C_ZOUT_0002 type ZDE_PARAM_ID1 value 'ZOUT_0002' ##NO_TEXT.
  constants C_ZOUT_0003 type ZDE_PARAM_ID1 value 'ZOUT_0003' ##NO_TEXT.
  constants C_ZOUT_0004 type ZDE_PARAM_ID1 value 'ZOUT_0004' ##NO_TEXT.
  constants C_ZOUT_0005 type ZDE_PARAM_ID1 value 'ZOUT_0005' ##NO_TEXT.
  constants C_ZOUT_0006 type ZDE_PARAM_ID1 value 'ZOUT_0006' ##NO_TEXT.
  constants C_ZOUT_0007 type ZDE_PARAM_ID1 value 'ZOUT_0007' ##NO_TEXT.
  constants C_ZOUT_0008 type ZDE_PARAM_ID1 value 'ZOUT_0008' ##NO_TEXT.
  constants C_ZOUT_0009 type ZDE_PARAM_ID1 value 'ZOUT_0009' ##NO_TEXT.
  constants C_ZOUT_0010 type ZDE_PARAM_ID1 value 'ZOUT_0010' ##NO_TEXT.
  constants C_ZRFUI_0001 type ZDE_PARAM_ID1 value 'ZRFUI_0001' ##NO_TEXT.
  constants C_ZRFUI_0002 type ZDE_PARAM_ID1 value 'ZRFUI_0002' ##NO_TEXT.
  constants C_ZRFUI_0003 type ZDE_PARAM_ID1 value 'ZRFUI_0003' ##NO_TEXT.
  constants C_ZRFUI_0004 type ZDE_PARAM_ID1 value 'ZRFUI_0004' ##NO_TEXT.
  constants C_ZRFUI_0005 type ZDE_PARAM_ID1 value 'ZRFUI_0005' ##NO_TEXT.
  constants C_ZRFUI_0006 type ZDE_PARAM_ID1 value 'ZRFUI_0006' ##NO_TEXT.
  constants C_ZVCE_0001 type ZDE_PARAM_ID1 value 'ZVCE_0001' ##NO_TEXT.
  constants C_VIND type ZDE_PARAM_ID2 value 'VIND' ##NO_TEXT.
  constants C_VINV type ZDE_PARAM_ID2 value 'VINV' ##NO_TEXT.
  constants C_ZVCE_0002 type ZDE_PARAM_ID1 value 'ZVCE_0002' ##NO_TEXT.
  constants C_HTS_CODE type ZDE_PARAM_ID2 value 'HTS_CODE' ##NO_TEXT.
  constants C_ZVCE_0003 type ZDE_PARAM_ID1 value 'ZVCE_0003' ##NO_TEXT.
  constants C_ADD_SERVICE type ZDE_PARAM_ID2 value 'ADDITIONAL_SERVICE' ##NO_TEXT.
  constants C_ZGEN_0007 type ZDE_PARAM_ID1 value 'ZGEN_0007' ##NO_TEXT.
  constants C_WC_MASTERCARTON_PACK type ZDE_PARAM_ID2 value 'WC_MASTERCARTON_PACK' ##NO_TEXT.
  constants C_BACKUP_SRV_TYPE type ZDE_PARAM_ID2 value 'BACKUP_SRV_TYPE' ##NO_TEXT.
  constants C_ZCROSS_0006 type ZDE_PARAM_ID1 value 'ZCROSS_0006' ##NO_TEXT.
  constants C_CONDTAB_IBD type ZDE_PARAM_ID2 value 'CONDTAB_0IBD' ##NO_TEXT.
  constants C_CONDTAB_ZSLO type ZDE_PARAM_ID2 value 'CONDTAB_ZSLO' ##NO_TEXT.
  constants C_CONDTYPE_ZSLO type ZDE_PARAM_ID2 value 'CONDTYPE_ZSLO' ##NO_TEXT.
  constants C_CONDTYPE_0IBD type ZDE_PARAM_ID2 value 'CONDTYPE_0IBD' ##NO_TEXT.
  constants C_ZMFS_0001 type ZDE_PARAM_ID1 value 'ZMFS_0001' ##NO_TEXT.
  constants C_MFS_PACKING3_LGTYP type ZDE_PARAM_ID2 value 'MFS_PACKING3_LGTYP' ##NO_TEXT.
  constants C_MFS_ACT_TYPE type ZDE_PARAM_ID2 value 'MFS_ACT_TYPE' ##NO_TEXT.
endinterface.
